dist: trusty
language: php
php:
  #- 5.6
  - 7.0

env:
  - TEST_SUITE=unittests
  - TEST_SUITE=ecgcodingstandard
  - TEST_SUITE=marketplaceeqp

before_script:
  - sleep 60

script:
  - cd ..
  - wget https://gist.githubusercontent.com/centerax/5e42abec89d62a1308ba/raw/4b3242361c0690e234266afb3520c2940ac1055a/auth.json
  - /bin/cp auth.json ~/.composer/
  - composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition
  - mkdir -p project-community-edition/app/code/Ebizmarts/Mandrill
  - /bin/cp -r magento2-mandrill/* project-community-edition/app/code/Ebizmarts/Mandrill
  - sh -c "if [ '$TEST_SUITE' = 'unittests' ]; then cd project-community-edition && /bin/cp app/code/Ebizmarts/Mandrill/phpunit_config.xml dev/tests/unit/ && ./vendor/bin/phpunit -c dev/tests/unit/phpunit_config.xml app/code/Ebizmarts/Mandrill/Test/Unit --coverage-text; fi"
  - sh -c "if [ '$TEST_SUITE' = 'ecgcodingstandard' ]; then cd project-community-edition && composer require --prefer-source --no-interaction "mandrill/mandrill=1.0.*" "squizlabs/php_codesniffer=2.8.*" "magento-ecg/coding-standard=^2.0" && vendor/squizlabs/php_codesniffer/scripts/phpcs --config-set installed_paths vendor/magento-ecg/coding-standard && ./vendor/squizlabs/php_codesniffer/scripts/phpcs -n --standard="EcgM2" app/code/Ebizmarts/Mandrill/; fi"
  - sh -c "if [ '$TEST_SUITE' = 'marketplaceeqp' ]; then cd project-community-edition && composer require --prefer-source --no-interaction "squizlabs/php_codesniffer=2.8.*" magento/marketplace-eqp && vendor/squizlabs/php_codesniffer/scripts/phpcs --config-set installed_paths vendor/magento/marketplace-eqp && ./vendor/squizlabs/php_codesniffer/scripts/phpcs -n --standard="MEQP2" app/code/Ebizmarts/Mandrill/; fi"

notifications:
  slack: ebizmarts:DqCqxnqWzW55zoFU069hxs1T
